### ISSUE TITLE
Upload & store the finished artboard somewhere

### ISSUE THREAD

**Issue by erasmus** [degeist/book-cover-generator#11]

**Comment by avorio** [comment]
Using Cloudinary, move forward:
- [ ] Implement [Cloudinary's Python API](https://github.com/cloudinary/pycloudinary)
- [ ] Provide an endpoint for the image upload form used in the modal
- [ ] Return all necessary data for artboard sharing, etc.

See also:

http://cloudinary.com/documentation/django_integration
http://cloudinary.com/documentation/jquery_image_upload
http://cloudinary.com/documentation/image_transformations
https://github.com/cloudinary/cloudinary_js

**Comment by avorio** [comment]
I'm working on branch `artboard-model`. There's an associated PR #24.

Once you're up to date in the branch, the following tasks are necessary:
- [ ] Install all dependencies: `pip install -r requirements.txt`
- [ ] Install Postgres (I strongly suggest [this app](http://postgresapp.com) for your local environment)
- [ ] Within `psql`, run: `create database danandphil;`
- [ ] Run Django migrations to populate database: `python manage.py migrate`

Once done, the upload tool will be available at `/upload/`.

**Comment by avorio** [comment]
@rashagen Check out the upload engine at:

https://danandphil-pr-24.herokuapp.com/upload/

I've implemented two methods:
1. Upload through our server
2. Direct upload via AJAX

Both methods will generate an Artboard object in the backend, which in time we will extend with other info such as the user-generated text, cutout option, etc. It's all timestamped and linked to the uploaded image, which now will live in Cloudinary. It's looking pretty amazing already.

But now it's over to you :)

**Comment by erasmus** [comment]
It's glorious! I'm integrating it in the artboard UI. Work in progress --> https://github.com/degeist/book-cover-generator/tree/11-integrate-cloudinary

You used some nice python templating in the (the blocks) in your upload example. Should we use this more?

**Comment by erasmus** [comment]
Basic UI version is now live. Style updates coming soon. Closing this.
