### ISSUE TITLE
Deploy app to Heroku

### ISSUE THREAD

**Issue by avorio** [degeist/book-cover-generator#13]
Ras,

I finally managed to tame the beast.

The app has been deployed to:

https://danandphil-pr-12.herokuapp.com/

This is pulling changes directly from Pull Request #12, which is now linked to the `deployment` branch. Any changes committed to that branch will get picked up automatically by Heroku. You can see the build progress in their dashboard. Here’s the output of the latest version:

https://dashboard.heroku.com/apps/danandphil-pr-12/activity/builds/352c4288-83e8-49f4-9b3c-0787132297db
### Absolute vs. relative paths

SO, as you can see, the app is not working properly. That’s because the static assets are aaaaaall over the place. You have used relative AND absolute paths in your code, which is a NO NO here. ALL paths should be relative, please.

Here’s a tiny change I made to `main.css`: e4339f2b6280e8ccb495a2b27c0e1e78d3957489

Basically, all references to files are taken very seriously by Django and if that file is not found, the whole thing falls apart and does not get built. That’s because of the way static files are served by the server.
### Templates

Another thing: templates. Django works with templates. So, the home page, for example, is pointing to the `home.html` file, which you’ll find inside the `bcg/templates` directory.

https://github.com/degeist/book-cover-generator/blob/deployment/bcg/templates/home.html

Please note how on the first line of that file I made a reference to `staticfiles`, which is the module that will take care of building all paths and ensuring that the files are located where they’re supposed to be:

https://github.com/degeist/book-cover-generator/blob/deployment/bcg/templates/home.html#L1

Later on, whenever referencing a static file, you should invoke the `staticfiles` module, as you see here:

https://github.com/degeist/book-cover-generator/blob/deployment/bcg/templates/home.html#L13

These two lines are the only lines I changed from your original file. I’ll let you adjust the other references and remove all absolute paths. Once you’ve done that, the app should work just like it was working before locally.

AH! I cried a bit when I saw hard-coded references to `localhost`. Please let’s make them disappear ;)

ALSO, why the hell do you have 20,000+ lines in `index.html`? Was that Jekyll having fun?
## Next steps
- [x] Remove all hard-coded references to `localhost`
- [x] Turn all absolute paths into relative paths using `staticfiles`
- [x] Remove unnecessary 20,000 lines of code from `index.html`

**Comment by erasmus** [comment]
Thanks for this. I'm aware of the hardcoded localhost + absolute/relative path - it's all from the Jekyll build. It's due to some specific workarounds for pushing to Github Pages w Jekyll. Legacy stuff, will remove.

**Comment by avorio** [comment]
Great! Thank you.

I was also aware that your workflow might not work as before now that we have Django and Django templates on the way. I'm sorry about that, as I'm not sure how you could address that. For now, as we only have a few static files, I suspect that might not be a total catastrophe, but in the long term... 

Have you any thoughts on this?

**Comment by erasmus** [comment]
This will always be a one-page app with a couple of modals, so nothing that can't be solved without templating. I just need to compile the SASS, not touching CSS. I can do that locally.

**Comment by avorio** [comment]
Wonderful! Let me know how that goes :)

**Comment by erasmus** [comment]
We're only using the `_site` directory now, correct?

**Comment by avorio** [comment]
No. That directory never reaches the web, actually. See my original post above.

`home.html` is the template loaded when the root URL is called:

https://github.com/degeist/book-cover-generator/tree/deployment/bcg/templates

And all the other static files are here:

https://github.com/degeist/book-cover-generator/tree/deployment/bcg/static

By the way, I had left the `index.html` in the `static/` directory. It shouldn't be there, as `home.html` is the replacement file within the `templates/` folder. I just pushed a [commit with that change](https://github.com/degeist/book-cover-generator/commit/f4785a57f7fa1c376cdb16a2acfb442736a17f76).

**Comment by erasmus** [comment]
I mean, nothing should be in root. We should clean it all up except the _SASS folder and the LICENSE / README

**Comment by erasmus** [comment]
Okay, got the app working locally with `DEBUG = True` (3cb64b73f1d3a6de574c7bac9299e54e72a47965). Static files are served  locally. With `DEBUG = False`, however, we get a 500 Error (removing all references to static files makes the app work, so it's an issue with the staticfiles). Also on the staging heroku app . This shouldn't happen as the web server should handle the serving of the static setup. 

I've tried running `$ python manage.py runserver --insecure` and messing around with e.g. `urls.py` to set the proper redirects. Nothing worked. Only setting `DEBUG = True`. Strange.

**Suggestions:**
- Better logging via `heroku config:set DEBUG_COLLECTSTATIC=1` (https://devcenter.heroku.com/articles/django-assets)
- Issue with `db.sqlite3` ?
- Go back to prev commit (before my clean-up branch)

_(For my own references)_
https://docs.djangoproject.com/en/1.9/howto/static-files/
https://docs.djangoproject.com/en/1.9/ref/contrib/staticfiles/

**Comment by avorio** [comment]
I think I know what’s causing this!

When `DEBUG=True`, Django serves static files. However, when `DEBUG=False` —in other words, when it’s a production environment—, `WhiteNoise` (an external Python library) serves all the static files. This might be the source of the inconsistency mentioned above. What we can do is to force `WhiteNoise` to serve even when it’s in development mode. I’ll make that change now, 2 secs.

**Comment by avorio** [comment]
So, all set!

https://danandphil-pr-12.herokuapp.com/ is now working as it should, and `Debug=False`.

When working locally, switch `Debug=True` and you should be fine.

**Comment by erasmus** [comment]
Fixed by f7e1fb9bb2908003f6e5537558c189ca40fc4f48. Closing
