### ISSUE TITLE
One img file (loaded with JS) still gets 404 on Heroku staging

### ISSUE THREAD

**Issue by erasmus** [degeist/book-cover-generator#19]
One file, which gets called via JS when clicking on it in the modal, can't be found on https://danandphil-pr-12.herokuapp.com/. 

Console log: 

``````
https://danandphil-pr-12.herokuapp.com/static/img/artboard/backgrounds/dummy-bg1.9fedffbf9f93.jpg Failed to load resource: the server responded with a status of 404 (Not Found) ```

``````

**Comment by avorio** [comment]
How are you calling that file, exactly? Are you using the `static` template tag?

Have you tried deploying the app again? All the static files are 'compiled' as part of deployment.
