### ISSUE TITLE
Transform the artboard elements to one Cloudinary image

### ISSUE THREAD

**Issue by erasmus** [degeist/book-cover-generator#29]
When clicking the bottom button, the variables (text, cutout overlay and background image) from artboard should be used to generate an image on Cloudinary.

**Comment by avorio** [comment]
Here's how the Cloudinary URL is constructed:

```
http://res.cloudinary.com/geist/image/upload/l_<overlay_image_id>.png/l_text:helvetica_40_bold:<text_escaped>,g_south,y_100,co_rgb:FFFF0080/<background_image_id>.jpg
```

Example:

http://res.cloudinary.com/geist/image/upload/l_guys_ujyh0m.png/l_text:helvetica_40_bold:User-generated%0Atext%20goes%20here,g_south,y_100,co_rgb:FFFF0080/bg-1_ybsxie.jpg

**Comment by erasmus** [comment]
This issue may be too closely related to #30 to justify it's own ticket? Feel free to close, if you think so @avorio

**Comment by avorio** [comment]
Yep. Let's continue this in #30.
