### ISSUE TITLE
Development and deployment workflow

### ISSUE THREAD

**Issue by avorio** [degeist/book-cover-generator#35]
@rashagen I'm a bit confused by our development and deployment workflow.

I was just going through some your latest commits and noticed that you were still committing them into the `deployment` branch. Did you change that workflow after we briefly spoke on Skype? 'Cause from where I stand, that `deployment` branch is long gone. That branch was the space I created for us to sort out the deployment to Heroku. Once it was completed, I merged it into `master` and off it went.

Does that workflow make sense to you now, or do we need to adjust?

Happy to hear about how you'd like to work :)

**Comment by erasmus** [comment]
So, normally I work with feature releases, just to focus (I actually use Git Flow http://danielkummer.github.io/git-flow-cheatsheet/). Which I thought was the intention with the deployment branch. But we're just us 2 and would love to have an up-to-date master branch (client is looking over our shoulder on that branch, too), so let's stay close to `master`.

That means:
1. Branch from master for new feature
2. Merge into master when feature complete 

As simple as that :)

When we're live, we need to re-introduce a staging environment,  but let's worry about that when the day comes

**Comment by avorio** [comment]
Great! Thanks for the info.
