### ISSUE TITLE
Create the proper Cloudinary GET request for correctly transformed background image

### ISSUE THREAD

**Issue by erasmus** [degeist/book-cover-generator#42]
Okay, a first version of the Cloudinary URL is: http://res.cloudinary.com/geist/image/upload/l_static:dp-cutout4.png/l_static:danphil-headline.png,w_500,y_10,g_north/l_text:Open%20Sans_40_bold_center:asdfasdfasd%20fasdfasdfasdfasdfsadf%20asdfasdfdasdfasdfa,g_south,y_50,w_500,c_fit,co_rgb:FFFFFF/w_500,h_660,c_fill/bg-1.jpg

**Comment by erasmus** [comment]
@avorio fyi, I've created a folder on Cloudinary called `static` for the static assets (BGs, overlays)

**Comment by avorio** [comment]
Wonderful! This is great!

Well done on the double overlay. That's cool.
