### ISSUE TITLE
User can share their finished artboard on Facebook 

### ISSUE THREAD

**Issue by erasmus** [degeist/book-cover-generator#5]
Either via API or as Open Graph metadata on a new page

**Comment by erasmus** [comment]
@avorio To share via the Open Graph, I need the absolute URL of the generated artboard page. 

So, two variables come into play here:
- The site URL (we'll be live on some subdomain of www.dapgo.com I think)
- The generated full URL for the artboard.

Questions:
- [x] Can we set site URL as a GLOBAL_VAR depending on where we are deploying? 
- [x] How do I fetch the full URL for the artboard on the artboard view itself?

**Comment by avorio** [comment]
> Can we set site URL as a GLOBAL_VAR depending on where we are deploying?

Yes, absolutely. I've called it `SITE_URL` and I'm including it in the list of variables available in both `home.html` and artboard `view.html` templates. You can refer to it using:

```
{{ site_url }}
```

> How do I fetch the full URL for the artboard on the artboard view itself?

You can refer to it in the template directly using:

```
{{ request.build_absolute_uri }}
```

For simplicity's sake, I've deployed this as part of the `fix-issue-44` branch.

You can see an example of the above in template `bcg/templates/view.html` in 2d5fb4225a2c2639588a6d96ec891fa47ae37587.

**Comment by avorio** [comment]
Ah! For testing purposes, I've added the env var `SITE_URL=cover.dapgo.com` to the master deployment and PR #72. You can see its effects here, for example:

https://danandphil-pr-72.herokuapp.com/artboard/v1470085326/dsvhrf93yzp8uvj5bhfw.png/?cutout=dp-cutout1.png&text=go%20outside

**Comment by erasmus** [comment]
Reopening, as this - technically speaking - wasn't finished.
