### ISSUE TITLE
Deploy app 

### ISSUE THREAD

**Issue by erasmus** [degeist/book-cover-generator#61]
App should be deployed to: 

```
createacover.danandphilgooutside.com 
```

@avorio to liaise with Max (who hosts the main site) to sort out CNAME settings and redirect:

```
danandphilgooutside.com/createacover -> createacover.danandphilgooutside.com
```

Deployment date is August 3. App launch is August 4th.

**Comment by avorio** [comment]
Here's my email to Max:

> Hi Max,
> 
> I hope you’re having a great day!
> 
> Yes, it will be absolutely fine for us to host the site at createacover.danandphilgooutside.com as long as you are able to set up a CNAME record pointing to our servers.
> 
> An ‘A record’ is not recommended as we are working with always-changing IP addresses in our hosting platform.
> 
> The CNAME record you should add to the DNS settings of the domain danandphilgooutside.com is:
> 
> ```
> Record: CNAME
> Name: createacover.danandphilgooutside.com
> Target: danandphil.herokuapp.com.
> ```
> 
> NB: The trailing . on the target domain may or may not be required, depending on your DNS provider.
> 
> Let me know once you’ve made this change so that we can test things from our end. It’s important that you make this change to the DNS settings as soon as possible so that we can avoid DNS propagation issues during launch.
> 
> I look forward to hearing from you soon.
> 
> Very best wishes,
> 
> André

**Comment by avorio** [comment]
I received an error message back from Gmail:

> This is the mail system at host gateway24.websitewelcome.com.
> 
> I'm sorry to have to inform you that your message could not
> be delivered to one or more recipients. It's attached below.
> 
> For further assistance, please send mail to postmaster.
> 
> If you do so, please include this problem report. You can
> delete your own text from the attached returned message.
> 
> ```
>                The mail system
> ```
> 
> goldsoundz@gmail.com: host alt2.gmail-smtp-in.l.google.com[108.177.12.26]
>     said: 421-4.7.0 [192.185.51.36      15] Our system has detected an unusual
>     rate of 421-4.7.0 unsolicited mail originating from your IP address. To
>     protect our 421-4.7.0 users from spam, mail sent from your IP address has
>     been temporarily 421-4.7.0 rate limited. Please visit 421-4.7.0
>     https://support.google.com/mail/answer/81126 to review our Bulk Email 421
>     4.7.0 Senders Guidelines. y185si297777vka.120 - gsmtp (in reply to end of
>     DATA command)
> Reporting-MTA: dns; gateway24.websitewelcome.com
> X-Postfix-Queue-ID: 000EBF0B14BA7
> X-Postfix-Sender: rfc822; andre@degeist.com
> Arrival-Date: Tue,  2 Aug 2016 10:09:32 -0500 (CDT)
> 
> Final-Recipient: rfc822; goldsoundz@gmail.com
> Original-Recipient: rfc822;goldsoundz@gmail.com
> Action: failed
> Status: 4.7.0
> Remote-MTA: dns; alt2.gmail-smtp-in.l.google.com
> Diagnostic-Code: smtp; 421-4.7.0 [192.185.51.36      15] Our system has
>     detected an unusual rate of 421-4.7.0 unsolicited mail originating from
>     your IP address. To protect our 421-4.7.0 users from spam, mail sent from
>     your IP address has been temporarily 421-4.7.0 rate limited. Please visit
>     421-4.7.0  https://support.google.com/mail/answer/81126 to review our Bulk
>     Email 421 4.7.0 Senders Guidelines. y185si297777vka.120 - gsmtp

**Comment by avorio** [comment]
I just re-sent that original email message. Let's see if it sticks now.

**Comment by erasmus** [comment]
Thanks for re-sending. I suspect it's a weird forward on his part. I'll push it tomorrow if there's no reply.

**Comment by erasmus** [comment]
Max will set the CNAME records on Friday 05 Aug 2pm GMT+1

**Comment by avorio** [comment]
This has all been done. Closing now.
