### ISSUE TITLE
Scale up Heroku in preparation for launch

### ISSUE THREAD

**Issue by avorio** [degeist/book-cover-generator#79]
Standard 1X dynos
Mix with 2X and Performance
512 MB RAM
$25.00/dyno/month

Heroku Postgres Database
Standard 2
$200.00/mo

**Comment by avorio** [comment]
**We are currently at $225/mo.** I'll add more dynos/database power on Thursday and will monitor the server load closely over the weekend adding more resources if/when necessary.

**Comment by erasmus** [comment]
So they just told me that they said 50k+ visitors (I told them, this meant potentially to infinity....). I asked them what they expected. They say peak traffic may be 80k-100k (DP will launch some YouTube videos with 1MM views, perhaps next week, so if 10% of them will go and try it out, that'll be substantial load).

How much load can Heroku take?

**Comment by avorio** [comment]
Heroku can take as much load as we can afford, basically.

We can scale up or down as we see fit. It's a cloud platform, which means that we can commission and decommission servers as we go, on the fly. Within the allocated budget we can probably cope with such high load in the first few days, but if it stays that high for more than a week, we might need to revisit our hosting charges. It might be important to make them aware of that.

**Comment by avorio** [comment]
By the way, Heroku is backed by AWS, in case you didn't know.

**Comment by erasmus** [comment]
But will it scale dynamically or does it require constant monitoring and manual adjustment of the plan? We just need to make sure client sees uptime under the initial peak load, so we look good ;)

**Comment by avorio** [comment]
As it is right now, it needs manual adjustment and monitoring. There are solutions available to automate that, but they're rather expensive. I've already cancelled my Friday night plans to be around and watch the Penguim dance. No worries. I'll make sure we cope with the load.

**Comment by avorio** [comment]
So, for the record, I've decided to implement Adept Scale, which is a cloud monitoring solution. It watches how we're performing and adjusts dynos up/down accordingly.

It costs USD18/mo.

This means that we don't have to constantly watch for peaks in traffic. This also means that there's a small delay in responding to sudden load spikes. When a special campaign is running, we should still increase dynos manually and monitor accordingly to guarantee app availability without delays.
